### ISSUE TITLE
"Connect" button (top-left): Let's fix it.

### ISSUE THREAD

**Issue by prologic** [khlieng/dispatch#17]
We should consider doing something better with the top-left "Connect" button.

Currently when you are connected, the button's label remains "Connect".

Further; clicking on it is a bit unintuitive as it actually disconnect your current session (*I think*).

**Comment by prologic** [comment]
I can't label issue :/ If I could I'd add a `UI` label here.

**Comment by khlieng** [comment]
The title of it should probably be "Add network", it doesnt disconnect you.

**Comment by prologic** [comment]
Sounds good to me. Maybe it should just be a smaller "+" button to the bottom left in the left pane?

**Comment by prologic** [comment]
Keep this space that "Connect" uses for branding?

**Comment by azbshiri** [comment]
I can work on this
