### ISSUE TITLE
c.write and c.writef vs. c.out <- ...

### ISSUE THREAD

**Issue by prologic** [khlieng/dispatch#19]
You seem to have changed your mind at some point.

We have some instances of `c.write(....)` and `c.writef(...)` lying around that probably should use `c.out <- ...`:

```
$ grin -d vendor 'c\.(write|writef)\('
./irc/client.go:
   94 : 			c.write("QUIT")
  141 : 	c.write("PASS " + password)
  145 : 	c.write("NICK " + nick)
  149 : 	c.writef("USER %s 0 * :%s", username, realname)
./irc/conn.go:
  208 : 			go c.write("PONG :" + msg.LastParam())
./irc/conn_test.go:
  113 : 	c.write("test")
  117 : 	c.writef("test %d", 2)
```

**Comment by khlieng** [comment]
Its because i dont read from the out queue until RPL_WELCOME, so you can queue up commands before its ready.

**Comment by prologic** [comment]
Ahh that makes sense actually; fair enough :)
