### ISSUE TITLE
Cannot connect on the demo

### ISSUE THREAD

**Issue by veb** [khlieng/dispatch#21]
I'm getting `Error: tls: oversized record received with length 20306` when I try the demo.

![image](https://user-images.githubusercontent.com/376245/41511307-75d841c8-72c8-11e8-868d-c06cd00b970f.png)

**Comment by khlieng** [comment]
I think this is somehow related to the per-IP connection limit, which is like 5 or something on freenode.

**Comment by veb** [comment]
I tried it on another network then I closed the tab. The client is still connected, an hour later. Probably need to time out.

**Comment by khlieng** [comment]
Thats intended.
