### ISSUE TITLE
Proxy Support: Support X-Forwarded-For

### ISSUE THREAD

**Issue by jc6482** [khlieng/dispatch#26]
The websocket handler relies on the Websocket connection remote address.
This can be come broken if using behind a proxy or reverse proxy.

Can we add support for the X-Forwarded-For header?

I added something simple to the websocket_handler.go to make it work in my own environment.

 20   var address string
 21
 22   if r.Header.Get("X-Forwarded-For") != "" {
 23     address = r.Header.Get("X-Forwarded-For")
 24   }else{
 25     address = conn.RemoteAddr().String()
 26   }
 27
 28   h := &wsHandler{
 29     ws:    newWSConn(conn),
 30     state: state,
 31     addr:  address,
 32   }

**Comment by khlieng** [comment]
Could you submit a PR?
