### ISSUE TITLE
Add option to hide join/part messages

### ISSUE THREAD

**Issue by jheiselman** [khlieng/dispatch#27]
It would be nice to have an option either in the web UI for per-server connections or in the config for a global option to hide the join/part messages

**Comment by daftaupe** [comment]
I'd like to take this issue, but I would need a little help.
I added easily a check box on the model of the "Colored nicks" one, modifying Settings.js, but then I wonder what's the best way of properly hiding the messages. Should it be done in the Javascript too ?

**Comment by khlieng** [comment]
I had thought about just always collapsing join/part/quits instead of doing a hide option.

**Comment by daftaupe** [comment]
@khlieng, collapsing the messages sounds like a good idea too.
Actually I'm also using https://github.com/thelounge/thelounge, and they have 3 options :
- show the messages
- collapse them (condensed view)
- totally hide them

Maybe making them collapsed is a sane default.
