### ISSUE TITLE
minor issue with doku: reverse proxy and docker

### ISSUE THREAD

**Issue by poVoq** [khlieng/dispatch#42]
https://github.com/khlieng/dispatch/wiki/Reverse-proxy-configuration

```
address = "127.0.0.1"
port = 9999
```
does not work when running it with docker behind a reverse proxy like Traefik.

```
address = ""
port = 9999
```
works though.

**Comment by daftaupe** [comment]
@poVoq, I did update the instructions accorsing to your comment (also added the cli way).

The issue can be closed.
