### ISSUE TITLE
Odd capitalization issues with NickServ commands

### ISSUE THREAD

**Issue by poVoq** [khlieng/dispatch#56]
See:
https://github.com/oragono/oragono/issues/666

Regular commands for NickServ are not working unless strickly following capitalization in Dispatch. With HexChat there are no such issues on the same server.

**Comment by khlieng** [comment]
This was how /raw command shortcuts were implemented, mentioned here: https://github.com/khlieng/dispatch/releases/tag/v0.4, I'll make it send any command it doesn't recognize through to the IRC server instead, that should fix this.
