### ISSUE TITLE
dcc , xdcc support ?

### ISSUE THREAD

**Issue by omgbox** [khlieng/dispatch#60]
hello trying to get some anime, but having trouble figuring the correct syntax 

> /set get nick [Harunatsu] Boruto - Naruto the Movie - v2 [BD 720p-AAC][01688050].mkv

`You have a DCC pending, Set your client to receive the transfer. Type "/MSG Saika XDCC CANCEL" to abort the transfer. (150 seconds remaining until timeout)`

**Comment by khlieng** [comment]
This isnt currently supported and you cant really do DCC properly from a web browser.

**Comment by pidario** [comment]
It's not actually that difficult to implement: I tried on my PC a rough implementation and I successfully managed to download a file through XDCC. This is easily done if you are ok with the file being saved to a directory of the server which is running dispatch. If you need the file to be streamed to the browser, things get more complicated, but I guess it should be doable through FileSystem API (or a polyfill), like https://mega.nz does.
I don't know when I will get some time do do it properly, but would you, @khlieng, accept a pull request?

**Comment by khlieng** [comment]
Sure, for streaming it should be possible to make it just behave like a regular file download aswell.

**Comment by pidario** [comment]
Yes, it shouldn't be too hard. Okay then, I'll refer this issue from the pull request once I'm done so that anybody interested may follow as well.

**Comment by omgbox** [comment]
wonderful news, xdcc is heavily used all over the world. 

could i also suggest, user hosting dispatch, could allow users to access this feature, or turn it off on through the webui. 

something as /set xdcc off --user:NinjaCat

**Comment by khlieng** [comment]
Possibly, I think it will be a flag in the config file initially.

**Comment by pidario** [comment]
> wonderful news, xdcc is heavily used all over the world.
> 
> could i also suggest, user hosting dispatch, could allow users to access this feature, or turn it off on through the webui.
> 
> something as /set xdcc off --user:NinjaCat

I'm not sure I got what you meant. Why in your example did you provide a user option? To disable the feature (autoget) for just that user? Usually in other IRC client you basically turn autoget on or off via config file as suggested by the maintainer, and this is the path I was going to take.

**Comment by khlieng** [comment]
Well there is a database, but we should probably just keep this a global setting for now.

**Comment by omgbox** [comment]
auto get will be accessible globally for everyone, it would make sense to allow certain users or groups on the channel to have access to auto get .

**Comment by pidario** [comment]
I started with the first of probably many commit, if you're curious you can have a peek here: https://github.com/pidario/dispatch/tree/feat/dcc-support
Downloads are working but I have to link the web interface which is still not aware of what's going on. Besides I probably didn't follow all your code patterns, @khlieng, but I guess all this stylistic stuff will be polished on PR.

**Comment by khlieng** [comment]
Nice, instead of adding stuff to the parser you could do a `ToCTCP() *CTCP` on the Message struct that checks for and strips 0x01 or returns nil if its not a CTCP message, then use that on NOTICE/PRIVMSG.

**Comment by pidario** [comment]
Sure, good idea.

**Comment by pidario** [comment]
As you suggested, I tried sending for each cycle the download progress as a Notice. The point is that this is really slow: the file (300 kB) takes just an instant to download (I set up an IRC server on my LAN to test things out) but the websocket can't keep up (I don't really know if there is some sort of timeout that limits the number of message you can receive per time unit or it's a limitation of the browser) and from the client perspective it looks as if the download takes 3-4 minutes to complete. Any suggestion? Websocket and client side stuff are not really my deal.

**Comment by khlieng** [comment]
You are sending the messages through the IRC server which is probably doing some throttling, not sure where i suggested this :)

**Comment by pidario** [comment]
I might have misunderstood, sorry about that. How do you suggest I notice the web interface about the download?

**Comment by khlieng** [comment]
So communication with the web UI happens in irc_handler.go and websocket_handler.go using `state.sendJSON()`, you could probably add some sort of file updates channel to the IRC client and then read from that in `run()` in irc_handler. You could then send "fake" DMs to the web UI with `i.state.sendJSON("pm", Message{})`, when the file is ready you would send a download link aswell. Later on I'll do a Files UI where you can manage file uploads and XDCC downloads.

Now might be a good time to get your branch updated with the latest from upstream master.

**Comment by pidario** [comment]
Indeed, thanks. I still have to go through some stuff, like file resume and I think we'll be good to go.
