### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by prologic** [khlieng/dispatch#7]
Spun up the latest version of dispatch over here at https://chat.mills.io/

Notice one important useability issue:

If you enter an invalid nickname; e.g: "Foo Bar" -- something with a space; things just don't work very well at all!

**Comment by khlieng** [comment]
Which server are you running? Most servers just chop off the rest of the nick or send an error message. I'll add some validation for this.

**Comment by prologic** [comment]
Do you listen for any of the nick error replies?

ERR_ERRONEUSNICKNAME
ERR_NICKNAMEINUSE
ERR_NICKCOLLISSION

if not should probably catch these? But having input validation on the nick
field would help prevent this too.

FWIW I am using a custom ircd backing https://irc.mills.io/ but that
shouldn't matter to you.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Sun, Nov 12, 2017 at 12:44 PM, Ken-Håvard Lieng <notifications@github.com

**Comment by prologic** [comment]
Ho nice? This has been fixed? I'll update my instances and test :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
