### ISSUE TITLE
Demo/main site is down

### ISSUE THREAD

**Issue by t0xic0der** [khlieng/dispatch#93]
https://dispatch.khlieng.com/ is no longer accessible for me. Can anyone confirm this too?

**Comment by khlieng** [comment]
Yes its down, will fix soon.

**Comment by daftaupe** [comment]
Anything can be done in order to help ?

**Comment by khlieng** [comment]
Its back up now, the server is in a SASL only IP range on libera though (I think even their own webclients are).
