### ISSUE TITLE
Official IRC channel

### ISSUE THREAD

**Issue by daftaupe** [khlieng/dispatch#96]
Hi,

I remember there was a channel on Freenode, but due to what happened on this network, I took the opportunity to reserve the #dispatch on https://libera.chat/, I can give it back / add people as admin.

I guess it would be cool to have a presence somewhere there for an irc client :)

If that's ok, maybe we could add this info somewhere on the REAMDE or something ?

**Comment by khlieng** [comment]
Nice 🙂

I added a line to the readme, it will also be the default in the demo once that gets back up.
